### ISSUE TITLE
feature: Create a bug list contributing to the feature freeze

### ISSUE THREAD

**Issue by adaviloper** [ccaglak/phptools.nvim#1]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

The readme lists a feature freeze. I'm curious what is blocking the development of this plugin.

### Describe the solution you'd like

A list of known bugs causing the feature freeze.

### Describe alternatives you've considered

N/a

**Comment by ccaglak** [comment]
Hi Adrian, currently there isn't any known issues.  Reason for feature freeze was to make sure everything is working before adding new features, as of next week i will be implementing new features. if you have any feature ideas or want to contribute please do. Have a wonderful day.

**Comment by adaviloper** [comment]
I'm super new at Neovim plugin development, but I was wondering if something similar to what I've started accumulating [here](https://github.com/adaviloper/php-dev-tools.nvim/blob/main/lua/php-dev-tools/init.lua#L8-L128) before finding this plugin would be useful.

The selected bit is a naive attempt at jumping to a method definition on a class based on array tuples as is similarly declared in route files. I'm not super familiar with the nvim API or working with other LSP features, so I'm sure this could be improved.

**Comment by adaviloper** [comment]
The current implementation uses Treesitter to make sure the current tuple under the cursor is a string as the second element and a class_constant_access_expression as the first element. If successful, it'll go to that file and jump to the method definition.

There are a few bugs and I'm not aware at the moment on how to effectively utilize the LSP to complement this functionality.
