### ISSUE TITLE
bug: Namespace generation is incorrect on some situations

### ISSUE THREAD

**Issue by aluisiora** [ccaglak/phptools.nvim#3]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 14.6.1

### Describe the bug

The namespace is being generated with the full path of the file. For this example I created this new file `Bar.php` under `app/Foo`, saved it `:w` and ran `:PhpCreate` and selected `class`. This is what was generated:
 
<img width="820" alt="Screenshot 2024-08-27 at 16 36 31" src="https://github.com/user-attachments/assets/8132a25e-ee4f-47d9-b532-1f7ba1e84860">

I suspect that this is due to the dash `-` in my path or something similar, but I'm not sure.

### Steps To Reproduce

1. Create a new project directory that includes a dash `-` in the name.
2. Create a new php file under a directory.
3. Save the new file.
4. Run :PhpCreate and select any option.

### Expected Behavior

Generate the namespace based on project root and psr-4 settings from `composer.json`.

**Comment by aluisiora** [comment]
I just confirmed that, without the dash, the namespace gets generated correctly:
<img width="691" alt="Screenshot 2024-08-27 at 16 44 04" src="https://github.com/user-attachments/assets/d6491e9d-7064-45d0-9b13-4bea98d307ad">

**Comment by ccaglak** [comment]
Thanks Aluisio, finded another bug related when there is forward slash it doesn't generate correct namespace.
ill post the fix very soon.
